/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//sw "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	//

	sw "github.com/CircleCI-Public/sample-go-cfd/go"
)

func main() {
	log.Printf("Server started")

	if err := sw.OpenDb(); err != nil {
		panic(err)
	}

	sw.SeedMenuItems()

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
