/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

// AddMenuItem - Create a menu item
func AddMenuItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListMenu - List all menu items
func ListMenu(c *gin.Context) {
	var menuiItems []MenuItem
	DB.Find(&menuiItems)

	c.JSON(http.StatusOK, menuiItems)
}

// ShowMenuItemById - Info for a specific menu item
func ShowMenuItemById(c *gin.Context) {
	id := c.Param("itemId")
	result, _ := strconv.Atoi(id)

	var menuiItems []MenuItem
	DB.Find(&menuiItems)

	for _, mi := range menuiItems {
		x := int(mi.ID)
		if x == result {
			DB.Find(&mi)
			c.JSON(http.StatusOK, mi)
			return
		}
	}

	c.JSON(http.StatusNotFound, gin.H{"message": "menu item not found"})
}
