/*
 * Continous Food Delievery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	corsConfig := cors.DefaultConfig()

	corsConfig.AllowOrigins = []string{"*"}
	// To be able to send tokens to the server.
	corsConfig.AllowCredentials = true

	// OPTIONS method for ReactJS
	corsConfig.AddAllowMethods("POST, GET, OPTIONS, PUT, DELETE")

	// Register the middleware
	router.Use(cors.New(corsConfig))
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	router.Static("/CFD/1.0.0/ui/", "swaggerui")

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/CFD/1.0.0/",
		Index,
	},

	{
		"AddCartItem",
		http.MethodPost,
		"/CFD/1.0.0/cart",
		AddCartItem,
	},

	{
		"DeleteCartItem",
		http.MethodDelete,
		"/CFD/1.0.0/cart/:itemId",
		DeleteCartItem,
	},

	{
		"ListCart",
		http.MethodGet,
		"/CFD/1.0.0/cart",
		ListCart,
	},

	{
		"AddImage",
		http.MethodPost,
		"/CFD/1.0.0/image",
		AddImage,
	},

	{
		"DeleteImage",
		http.MethodDelete,
		"/CFD/1.0.0/image/:imageId",
		DeleteImage,
	},

	{
		"GetImage",
		http.MethodGet,
		"/CFD/1.0.0/image/:imageId",
		GetImage,
	},

	{
		"AddMenuItem",
		http.MethodPost,
		"/CFD/1.0.0/menu",
		AddMenuItem,
	},

	{
		"ListMenu",
		http.MethodGet,
		"/CFD/1.0.0/menu",
		ListMenu,
	},

	{
		"ShowMenuItemById",
		http.MethodGet,
		"/CFD/1.0.0/menu/:itemId",
		ShowMenuItemById,
	},

	{
		"GetTestMenuItems",
		http.MethodGet,
		"/testmenuitems",
		GetTestMenuItems,
	},
}

func GetTestMenuItems(c *gin.Context) {
	c.JSON(http.StatusOK, menuItems)
}

var menuItems = []MenuItem{
	{ID: 0, Description: "This is desc test 1", Name: "testname 1", Price: 1.99},
	{ID: 1, Description: "This is desc test 2", Name: "testname 2", Price: 2.99},
	{ID: 2, Description: "This is desc test 3", Name: "testname 3", Price: 3.99},
}
